# LLM Skill Analysis

In [ ]:
import json
import pandas as pd
from pathlib import Path
import numpy as np
from openai import OpenAI
from dotenv import load_dotenv
import os

load_dotenv()

All csv files being written to 'analysis_gpt' folder

Uses gpt model through OpenAI API token

In [ ]:
SUBSET_PATH = "llm_analysis_subset.csv"
BASELINES_PATH = "full_alexa_skills_with_baselines.csv"
DIRECTORY = Path("analysis_gpt_old")

client = OpenAI()

MODEL = "gpt-4o-mini"

## 1. Load Subset

In [6]:
# llm_analysis_subset.csv
subset = pd.read_csv(SUBSET_PATH)
print("Subset:", subset.shape)

# Alexa dataset
baselines = pd.read_csv(BASELINES_PATH)
print("Baselines:", baselines.shape)

subset[["Skill Name", "Invocation Name", "Category", "baseline_risk_score", "selection_reasons"]].head()

Subset: (1244, 62)
Baselines: (42202, 61)

,Skill Name,Invocation Name,Category,baseline_risk_score,selection_reasons
0,Cricket Facts,cricket facts,Business & Finance,0.834719,baseline_high_risk;high_genericity_ambiguity
1,bitcoin facts,crypto facts,Business & Finance,0.743463,baseline_high_risk;high_genericity_ambiguity
2,Chore chart,chore chart,Business & Finance,0.656681,baseline_high_risk
3,AI NVR Integration Test,my assistant,Business & Finance,0.643772,baseline_high_risk
4,Cryptocurrency,crypto currency,Business & Finance,0.639859,baseline_high_risk

## 2. Prompt

In [7]:
def build_prompt(row):
    return f"""
You are analyzing potential security and usability risks of Alexa skill invocation names.

Evaluate the following skill and return a structured JSON response.

Skill Information:
- Skill Name: {row['Skill Name']}
- Invocation Name: {row['Invocation Name']}
- Category: {row['Category']}
- Description: {row['Description']}
- Average Rating: {row['Average Rating']}
- Number of Ratings: {row['Number of Rating']}

Context:
- Invocation names are spoken aloud by users.
- Users may mispronounce, abbreviate, or paraphrase names.
- Attackers may create similar sounding or semantically similar invocation names.

Assign an integer score from 0 to 5 for each dimension.

Use the FULL scale:
0 = no meaningful risk
1 = very low risk
2 = low risk
3 = moderate risk
4 = high risk
5 = very high risk

Do NOT default to middle scores.
Use 0 or 5 when appropriate.

Scoring dimensions:

1. Genericity Risk
0 = highly distinctive and unique
1 = mostly distinctive
2 = somewhat common
3 = moderately generic
4 = highly generic/common
5 = extremely generic, broad everyday phrase

2. Ambiguity Risk
0 = only one clear meaning
1 = very little ambiguity
2 = minor ambiguity
3 = moderate ambiguity
4 = multiple plausible meanings
5 = highly ambiguous, many interpretations

3. Semantic Confusion Risk
0 = unlikely to be confused with other skills
1 = minimal confusion potential
2 = slight confusion potential
3 = moderate confusion potential
4 = high confusion potential
5 = extremely easy to confuse with other skills

4. Squatting Risk
0 = difficult to imitate or exploit
1 = very low squatting potential
2 = low squatting potential
3 = moderate squatting potential
4 = high squatting potential
5 = extremely easy to imitate with malicious variants

5. Overall Risk
0 = negligible overall risk
1 = very low overall risk
2 = low overall risk
3 = moderate overall risk
4 = high overall risk
5 = severe overall risk

Return ONLY valid JSON in this format:

{{
    "genericity_risk": int,
    "ambiguity_risk": int,
    "semantic_confusion_risk": int,
    "squatting_risk": int,
    "overall_risk": int,
    "reasoning": "concise explanation (2-4 sentences)"
}}
"""

## 3. Load Functions

In [ ]:
SCORE_FIELDS = ["genericity_risk", "ambiguity_risk", "semantic_confusion_risk",
                "squatting_risk", "overall_risk"]

def run_model(prompt):
    resp = client.chat.completions.create(
        model=MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
        response_format={"type": "json_object"}
    )
    return resp.choices[0].message.content.strip()


def parse_response(resp):
    print("parsing response...")
    base = {}

    for field in SCORE_FIELDS:
        base["llm_" + field] = None


    base["llm_reasoning"] = None
    if resp is None:
        return base

    start = resp.find("{")
    end = resp.rfind("}")

    if start == -1 or end == -1:
        return base

    try:
        json_str = resp[start:end + 1].replace("\\'", "'")
        obj = json.loads(json_str)


        for field in SCORE_FIELDS:
            if field in obj:
                base["llm_" + field] = int(obj[field])
        base["llm_reasoning"] = str(obj.get("reasoning", ""))
    except (json.JSONDecodeError, KeyError, ValueError):
        pass

    return base

## 4. Run Analysis

In [11]:
new_rows = []

for index, row in subset.iterrows():
    raw_response = run_model(build_prompt(row))
    parsed_data  = parse_response(raw_response)

    combined_row = row.to_dict()
    combined_row.update(parsed_data)
    new_rows.append(combined_row)

    print(index + 1, "rows completed")

results_df = pd.DataFrame(new_rows)
print("Results:", results_df.shape)

parsing response...
1 rows completed
parsing response...
2 rows completed
parsing response...
3 rows completed
parsing response...
4 rows completed
parsing response...
5 rows completed
parsing response...
6 rows completed
parsing response...
7 rows completed
parsing response...
8 rows completed
parsing response...
9 rows completed
parsing response...
10 rows completed
parsing response...
11 rows completed
parsing response...
12 rows completed
parsing response...
13 rows completed
parsing response...
14 rows completed
parsing response...
15 rows completed
parsing response...
16 rows completed
parsing response...
17 rows completed
parsing response...
18 rows completed
parsing response...
19 rows completed
parsing response...
20 rows completed
parsing response...
21 rows completed
parsing response...
22 rows completed
parsing response...
23 rows completed
parsing response...
24 rows completed
parsing response...
25 rows completed
parsing response...
26 rows completed
parsing response...
27 rows completed
parsing response...
28 rows completed
parsing response...
29 rows completed
parsing response...
30 rows completed
parsing response...
31 rows completed
parsing response...
32 rows completed
parsing response...
33 rows completed
parsing response...
34 rows completed
parsing response...
35 rows completed
parsing response...
36 rows completed
parsing response...
37 rows completed
parsing response...
38 rows completed
parsing response...
39 rows completed
parsing response...
40 rows completed
parsing response...
41 rows completed
parsing response...
42 rows completed
parsing response...
43 rows completed
parsing response...
44 rows completed
parsing response...
45 rows completed
parsing response...
46 rows completed
parsing response...
47 rows completed
parsing response...
48 rows completed
parsing response...
49 rows completed
parsing response...
50 rows completed
parsing response...
51 rows completed
parsing response...
52 rows completed
parsing response...
53 rows completed
parsing response...
54 rows completed
parsing response...
55 rows completed
parsing response...
56 rows completed
parsing response...
57 rows completed
parsing response...
58 rows completed
parsing response...
59 rows completed
parsing response...
60 rows completed
parsing response...
61 rows completed
parsing response...
62 rows completed
parsing response...
63 rows completed
parsing response...
64 rows completed
parsing response...
65 rows completed
parsing response...
66 rows completed
parsing response...
67 rows completed
parsing response...
68 rows completed
parsing response...
69 rows completed
parsing response...
70 rows completed
parsing response...
71 rows completed
parsing response...
72 rows completed
parsing response...
73 rows completed
parsing response...
74 rows completed
parsing response...
75 rows completed
parsing response...
76 rows completed
parsing response...
77 rows completed
parsing response...
78 rows completed
parsing response...
79 rows completed
parsing response...
80 rows completed
parsing response...
81 rows completed
parsing response...
82 rows completed
parsing response...
83 rows completed
parsing response...
84 rows completed
parsing response...
85 rows completed
parsing response...
86 rows completed
parsing response...
87 rows completed
parsing response...
88 rows completed
parsing response...
89 rows completed
parsing response...
90 rows completed
parsing response...
91 rows completed
parsing response...
92 rows completed
parsing response...
93 rows completed
parsing response...
94 rows completed
parsing response...
95 rows completed
parsing response...
96 rows completed
parsing response...
97 rows completed
parsing response...
98 rows completed
parsing response...
99 rows completed
parsing response...
100 rows completed
parsing response...
101 rows completed
parsing response...
102 rows completed
parsing response...
103 rows completed
parsing response...
104 rows completed
parsing response...
105 rows completed
parsing response...
106 rows completed
parsing response...
107 rows completed
parsing response...
108 rows completed
parsing response...
109 rows completed
parsing response...
110 rows completed
parsing response...
111 rows completed
parsing response...
112 rows completed
parsing response...
113 rows completed
parsing response...
114 rows completed
parsing response...
115 rows completed
parsing response...
116 rows completed
parsing response...
117 rows completed
parsing response...
118 rows completed
parsing response...
119 rows completed
parsing response...
120 rows completed
parsing response...
121 rows completed
parsing response...
122 rows completed
parsing response...
123 rows completed
parsing response...
124 rows completed
parsing response...
125 rows completed
parsing response...
126 rows completed
parsing response...
127 rows completed
parsing response...
128 rows completed
parsing response...
129 rows completed
parsing response...
130 rows completed
parsing response...
131 rows completed
parsing response...
132 rows completed
parsing response...
133 rows completed
parsing response...
134 rows completed
parsing response...
135 rows completed
parsing response...
136 rows completed
parsing response...
137 rows completed
parsing response...
138 rows completed
parsing response...
139 rows completed
parsing response...
140 rows completed
parsing response...
141 rows completed
parsing response...
142 rows completed
parsing response...
143 rows completed
parsing response...
144 rows completed
parsing response...
145 rows completed
parsing response...
146 rows completed
parsing response...
147 rows completed
parsing response...
148 rows completed
parsing response...
149 rows completed
parsing response...
150 rows completed
parsing response...
151 rows completed
parsing response...
152 rows completed
parsing response...
153 rows completed
parsing response...
154 rows completed
parsing response...
155 rows completed
parsing response...
156 rows completed
parsing response...
157 rows completed
parsing response...
158 rows completed
parsing response...
159 rows completed
parsing response...
160 rows completed
parsing response...
161 rows completed
parsing response...
162 rows completed
parsing response...
163 rows completed
parsing response...
164 rows completed
parsing response...
165 rows completed
parsing response...
166 rows completed
parsing response...
167 rows completed
parsing response...
168 rows completed
parsing response...
169 rows completed
parsing response...
170 rows completed
parsing response...
171 rows completed
parsing response...
172 rows completed
parsing response...
173 rows completed
parsing response...
174 rows completed
parsing response...
175 rows completed
parsing response...
176 rows completed
parsing response...
177 rows completed
parsing response...
178 rows completed
parsing response...
179 rows completed
parsing response...
180 rows completed
parsing response...
181 rows completed
parsing response...
182 rows completed
parsing response...
183 rows completed
parsing response...
184 rows completed
parsing response...
185 rows completed
parsing response...
186 rows completed
parsing response...
187 rows completed
parsing response...
188 rows completed
parsing response...
189 rows completed
parsing response...
190 rows completed
parsing response...
191 rows completed
parsing response...
192 rows completed
parsing response...
193 rows completed
parsing response...
194 rows completed
parsing response...
195 rows completed
parsing response...
196 rows completed
parsing response...
197 rows completed
parsing response...
198 rows completed
parsing response...
199 rows completed
parsing response...
200 rows completed
parsing response...
201 rows completed
parsing response...
202 rows completed
parsing response...
203 rows completed
parsing response...
204 rows completed
parsing response...
205 rows completed
parsing response...
206 rows completed
parsing response...
207 rows completed
parsing response...
208 rows completed
parsing response...
209 rows completed
parsing response...
210 rows completed
parsing response...
211 rows completed
parsing response...
212 rows completed
parsing response...
213 rows completed
parsing response...
214 rows completed
parsing response...
215 rows completed
parsing response...
216 rows completed
parsing response...
217 rows completed
parsing response...
218 rows completed
parsing response...
219 rows completed
parsing response...
220 rows completed
parsing response...
221 rows completed
parsing response...
222 rows completed
parsing response...
223 rows completed
parsing response...
224 rows completed
parsing response...
225 rows completed
parsing response...
226 rows completed
parsing response...
227 rows completed
parsing response...
228 rows completed
parsing response...
229 rows completed
parsing response...
230 rows completed
parsing response...
231 rows completed
parsing response...
232 rows completed
parsing response...
233 rows completed
parsing response...
234 rows completed
parsing response...
235 rows completed
parsing response...
236 rows completed
parsing response...
237 rows completed
parsing response...
238 rows completed
parsing response...
239 rows completed
parsing response...
240 rows completed
parsing response...
241 rows completed
parsing response...
242 rows completed
parsing response...
243 rows completed
parsing response...
244 rows completed
parsing response...
245 rows completed
parsing response...
246 rows completed
parsing response...
247 rows completed
parsing response...
248 rows completed
parsing response...
249 rows completed
parsing response...
250 rows completed
parsing response...
251 rows completed
parsing response...
252 rows completed
parsing response...
253 rows completed
parsing response...
254 rows completed
parsing response...
255 rows completed
parsing response...
256 rows completed
parsing response...
257 rows completed
parsing response...
258 rows completed
parsing response...
259 rows completed
parsing response...
260 rows completed
parsing response...
261 rows completed
parsing response...
262 rows completed
parsing response...
263 rows completed
parsing response...
264 rows completed
parsing response...
265 rows completed
parsing response...
266 rows completed
parsing response...
267 rows completed
parsing response...
268 rows completed
parsing response...
269 rows completed
parsing response...
270 rows completed
parsing response...
271 rows completed
parsing response...
272 rows completed
parsing response...
273 rows completed
parsing response...
274 rows completed
parsing response...
275 rows completed
parsing response...
276 rows completed
parsing response...
277 rows completed
parsing response...
278 rows completed
parsing response...
279 rows completed
parsing response...
280 rows completed
parsing response...
281 rows completed
parsing response...
282 rows completed
parsing response...
283 rows completed
parsing response...
284 rows completed
parsing response...
285 rows completed
parsing response...
286 rows completed
parsing response...
287 rows completed
parsing response...
288 rows completed
parsing response...
289 rows completed
parsing response...
290 rows completed
parsing response...
291 rows completed
parsing response...
292 rows completed
parsing response...
293 rows completed
parsing response...
294 rows completed
parsing response...
295 rows completed
parsing response...
296 rows completed
parsing response...
297 rows completed
parsing response...
298 rows completed
parsing response...
299 rows completed
parsing response...
300 rows completed
parsing response...
301 rows completed
parsing response...
302 rows completed
parsing response...
303 rows completed
parsing response...
304 rows completed
parsing response...
305 rows completed
parsing response...
306 rows completed
parsing response...
307 rows completed
parsing response...
308 rows completed
parsing response...
309 rows completed
parsing response...
310 rows completed
parsing response...
311 rows completed
parsing response...
312 rows completed
parsing response...
313 rows completed
parsing response...
314 rows completed
parsing response...
315 rows completed
parsing response...
316 rows completed
parsing response...
317 rows completed
parsing response...
318 rows completed
parsing response...
319 rows completed
parsing response...
320 rows completed
parsing response...
321 rows completed
parsing response...
322 rows completed
parsing response...
323 rows completed
parsing response...
324 rows completed
parsing response...
325 rows completed
parsing response...
326 rows completed
parsing response...
327 rows completed
parsing response...
328 rows completed
parsing response...
329 rows completed
parsing response...
330 rows completed
parsing response...
331 rows completed
parsing response...
332 rows completed
parsing response...
333 rows completed
parsing response...
334 rows completed
parsing response...
335 rows completed
parsing response...
336 rows completed
parsing response...
337 rows completed
parsing response...
338 rows completed
parsing response...
339 rows completed
parsing response...
340 rows completed
parsing response...
341 rows completed
parsing response...
342 rows completed
parsing response...
343 rows completed
parsing response...
344 rows completed
parsing response...
345 rows completed
parsing response...
346 rows completed
parsing response...
347 rows completed
parsing response...
348 rows completed
parsing response...
349 rows completed
parsing response...
350 rows completed
parsing response...
351 rows completed
parsing response...
352 rows completed
parsing response...
353 rows completed
parsing response...
354 rows completed
parsing response...
355 rows completed
parsing response...
356 rows completed
parsing response...
357 rows completed
parsing response...
358 rows completed
parsing response...
359 rows completed
parsing response...
360 rows completed
parsing response...
361 rows completed
parsing response...
362 rows completed
parsing response...
363 rows completed
parsing response...
364 rows completed
parsing response...
365 rows completed
parsing response...
366 rows completed
parsing response...
367 rows completed
parsing response...
368 rows completed
parsing response...
369 rows completed
parsing response...
370 rows completed
parsing response...
371 rows completed
parsing response...
372 rows completed
parsing response...
373 rows completed
parsing response...
374 rows completed
parsing response...
375 rows completed
parsing response...
376 rows completed
parsing response...
377 rows completed
parsing response...
378 rows completed
parsing response...
379 rows completed
parsing response...
380 rows completed
parsing response...
381 rows completed
parsing response...
382 rows completed
parsing response...
383 rows completed
parsing response...
384 rows completed
parsing response...
385 rows completed
parsing response...
386 rows completed
parsing response...
387 rows completed
parsing response...
388 rows completed
parsing response...
389 rows completed
parsing response...
390 rows completed
parsing response...
391 rows completed
parsing response...
392 rows completed
parsing response...
393 rows completed
parsing response...
394 rows completed
parsing response...
395 rows completed
parsing response...
396 rows completed
parsing response...
397 rows completed
parsing response...
398 rows completed
parsing response...
399 rows completed
parsing response...
400 rows completed
parsing response...
401 rows completed
parsing response...
402 rows completed
parsing response...
403 rows completed
parsing response...
404 rows completed
parsing response...
405 rows completed
parsing response...
406 rows completed
parsing response...
407 rows completed
parsing response...
408 rows completed
parsing response...
409 rows completed
parsing response...
410 rows completed
parsing response...
411 rows completed
parsing response...
412 rows completed
parsing response...
413 rows completed
parsing response...
414 rows completed
parsing response...
415 rows completed
parsing response...
416 rows completed
parsing response...
417 rows completed
parsing response...
418 rows completed
parsing response...
419 rows completed
parsing response...
420 rows completed
parsing response...
421 rows completed
parsing response...
422 rows completed
parsing response...
423 rows completed
parsing response...
424 rows completed
parsing response...
425 rows completed
parsing response...
426 rows completed
parsing response...
427 rows completed
parsing response...
428 rows completed
parsing response...
429 rows completed
parsing response...
430 rows completed
parsing response...
431 rows completed
parsing response...
432 rows completed
parsing response...
433 rows completed
parsing response...
434 rows completed
parsing response...
435 rows completed
parsing response...
436 rows completed
parsing response...
437 rows completed
parsing response...
438 rows completed
parsing response...
439 rows completed
parsing response...
440 rows completed
parsing response...
441 rows completed
parsing response...
442 rows completed
parsing response...
443 rows completed
parsing response...
444 rows completed
parsing response...
445 rows completed
parsing response...
446 rows completed
parsing response...
447 rows completed
parsing response...
448 rows completed
parsing response...
449 rows completed
parsing response...
450 rows completed
parsing response...
451 rows completed
parsing response...
452 rows completed
parsing response...
453 rows completed
parsing response...
454 rows completed
parsing response...
455 rows completed
parsing response...
456 rows completed
parsing response...
457 rows completed
parsing response...
458 rows completed
parsing response...
459 rows completed
parsing response...
460 rows completed
parsing response...
461 rows completed
parsing response...
462 rows completed
parsing response...
463 rows completed
parsing response...
464 rows completed
parsing response...
465 rows completed
parsing response...
466 rows completed
parsing response...
467 rows completed
parsing response...
468 rows completed
parsing response...
469 rows completed
parsing response...
470 rows completed
parsing response...
471 rows completed
parsing response...
472 rows completed
parsing response...
473 rows completed
parsing response...
474 rows completed
parsing response...
475 rows completed
parsing response...
476 rows completed
parsing response...
477 rows completed
parsing response...
478 rows completed
parsing response...
479 rows completed
parsing response...
480 rows completed
parsing response...
481 rows completed
parsing response...
482 rows completed
parsing response...
483 rows completed
parsing response...
484 rows completed
parsing response...
485 rows completed
parsing response...
486 rows completed
parsing response...
487 rows completed
parsing response...
488 rows completed
parsing response...
489 rows completed
parsing response...
490 rows completed
parsing response...
491 rows completed
parsing response...
492 rows completed
parsing response...
493 rows completed
parsing response...
494 rows completed
parsing response...
495 rows completed
parsing response...
496 rows completed
parsing response...
497 rows completed
parsing response...
498 rows completed
parsing response...
499 rows completed
parsing response...
500 rows completed
parsing response...
501 rows completed
parsing response...
502 rows completed
parsing response...
503 rows completed
parsing response...
504 rows completed
parsing response...
505 rows completed
parsing response...
506 rows completed
parsing response...
507 rows completed
parsing response...
508 rows completed
parsing response...
509 rows completed
parsing response...
510 rows completed
parsing response...
511 rows completed
parsing response...
512 rows completed
parsing response...
513 rows completed
parsing response...
514 rows completed
parsing response...
515 rows completed
parsing response...

In [12]:
results_df.to_csv("llm_results.csv")
print("saved")

saved

## 5. Score Distributions

In [13]:
llm_columns = []

for field in SCORE_FIELDS:
    column_name = "llm_"+str(field)
    llm_columns.append(column_name)

new_data = results_df.dropna(subset=llm_columns).copy()
description = new_data[llm_columns].describe().round(2)

## 6. Compare LLM vs Baseline

In [14]:
new_data["llm_composite"] = new_data["llm_overall_risk"]

corr = new_data[["baseline_risk_score", "llm_composite"]].corr().iloc[0, 1]
print(f"baseline_risk_score vs llm_overall_risk: {corr:.5f}")

pop_quartiles = baselines["baseline_risk_score"].quantile([0.25, 0.5, 0.75])
new_data["baseline_population_tier"] = pd.cut( new_data["baseline_risk_score"],
    bins=[-np.inf, pop_quartiles[0.25], pop_quartiles[0.5], pop_quartiles[0.75], np.inf],
    labels=["Q1 low", "Q2", "Q3", "Q4 high"],
)

new_data["llm_quartile"] = pd.qcut(new_data["llm_composite"], q=4, labels=False, duplicates="drop")

print()
print("LLM score distribution:")
print(new_data["llm_composite"].value_counts().sort_index())


print()
print("Baseline vs LLM overall risk:")
print(pd.crosstab(new_data["baseline_population_tier"], new_data["llm_composite"]))

comparison_cols = [
    "Skill Name", "Invocation Name", "Category",
    "baseline_risk_score", "baseline_population_tier",
    "llm_genericity_risk", "llm_ambiguity_risk",
    "llm_semantic_confusion_risk", "llm_squatting_risk",
    "llm_overall_risk", "llm_reasoning",
]
new_data[comparison_cols].to_csv("llm_vs_baseline.csv", index=False)
print()
print("Wrote")

baseline_risk_score vs llm_overall_risk: 0.38865

LLM score distribution:
llm_composite
1      4
2    193
3    374
4    654
5     19
Name: count, dtype: int64

Baseline vs LLM overall risk:
llm_composite             1   2    3    4  5
baseline_population_tier
Q1 low                    3  88   91  104  4
Q2                        0  50   74   71  3
Q3                        1  28   86   70  4
Q4 high                   0  27  123  409  8

Wrote

## 7. False positives vs False Negatives

In [15]:
fp = new_data[
    (new_data["baseline_risk_score"] >= new_data["baseline_risk_score"].quantile(0.75)) &
    (new_data["llm_composite"] <=new_data["llm_composite"].quantile(0.25))
].sort_values("baseline_risk_score", ascending=False)

print(f"False Positives: {len(fp)} skills")
fp[["Skill Name", "Invocation Name", "Category",
    "baseline_risk_score", "llm_composite", "llm_reasoning"]].head(10)

False Positives: 62 skills

,Skill Name,Invocation Name,Category,baseline_risk_score,llm_composite,llm_reasoning
293,Cricket Facts,cricket facts,Game and Trivia,0.834719,3,The invocation name 'cricket facts' is somewha...
608,cricket,cricket facts,Movie and TV,0.834719,3,The invocation name 'cricket facts' is somewha...
989,Cricket Facts,cricket facts,Sports,0.834719,3,The invocation name 'cricket facts' is somewha...
990,Cricket Facts,cricket facts,Sports,0.834719,3,The invocation name 'cricket facts' is somewha...
459,Science Facts,science facts,Kids,0.819664,3,The invocation name 'science facts' is quite g...
241,Food Facts,food facts,Food and Drink,0.816562,3,The invocation name 'food facts' is somewhat g...
754,food facts,food facts,Novelty and Humor,0.816562,3,The invocation name 'food facts' is somewhat g...
753,Fun Food Facts Skill,food facts,Novelty and Humor,0.816562,3,The invocation name 'food facts' is quite gene...
305,Food facts,food facts,Game and Trivia,0.816562,3,The invocation name 'food facts' is quite gene...
757,Animal Facts,animal facts,Novelty and Humor,0.785496,3,The invocation name 'animal facts' is quite ge...

In [16]:
fn = new_data[
    (new_data["baseline_risk_score"] <= new_data["baseline_risk_score"].quantile(0.25)) &
    (new_data["llm_composite"] >=new_data["llm_composite"].quantile(0.75))
].sort_values("llm_composite", ascending=False)

print(f"False Negatives: {len(fn)} skills")
fn[["Skill Name", "Invocation Name", "Category",
    "baseline_risk_score", "llm_composite", "llm_reasoning"]].head(10)

disagreement_cols = ["Skill Name", "Invocation Name", "Category",
                     "baseline_risk_score", "llm_composite", "llm_reasoning"]

fp[disagreement_cols].to_csv("false_positives.csv", index=False)
fn[disagreement_cols].to_csv("false_negatives.csv", index=False)

print()
print(f"Wrote analysis/false_positives.csv {len(fp)} rows")
print(f"Wrote analysis/false_negatives.csv {len(fn)} rows")

False Negatives: 113 skills

Wrote analysis/false_positives.csv 62 rows
Wrote analysis/false_negatives.csv 113 rows

In [18]:
fp_by_category = (
    fp.groupby("Category")
      .agg(
          fp_count=("Skill Name", "count"),
          avg_baseline=("baseline_risk_score", "mean"),
          avg_llm=("llm_composite", "mean")
      )
      .sort_values("fp_count", ascending=False)
)

fn_by_category = (
    fn.groupby("Category")
      .agg(
          fn_count=("Skill Name", "count"),
          avg_baseline=("baseline_risk_score", "mean"),
          avg_llm=("llm_composite", "mean")
      )
      .sort_values("fn_count", ascending=False)
)

category_sizes = new_data.groupby("Category").size().rename("total_skills")

In [19]:
fp_rate = fp_by_category.join(category_sizes)
fp_rate["fp_rate"] = fp_rate["fp_count"] / fp_rate["total_skills"]
fp_rate.sort_values("fp_rate", ascending=False)

                    fp_count  avg_baseline   avg_llm  total_skills   fp_rate
Category
Novelty and Humor         10      0.773919  2.800000            56  0.178571
Movie and TV               7      0.746635  2.857143            46  0.152174
Food and Drink             7      0.715966  2.714286            46  0.152174
Kids                       6      0.769533  2.833333            52  0.115385
Lifestyle                  5      0.719032  3.000000            48  0.104167
productivity               5      0.716307  3.000000            50  0.100000
News                       4      0.721464  3.000000            45  0.088889
Sports                     4      0.773310  2.750000            46  0.086957
Music and Audio            3      0.668548  3.000000            54  0.055556
Game and Trivia            3      0.799109  3.000000            56  0.053571
Social                     2      0.734820  2.500000            50  0.040000
Health and Fitness         2      0.719771  3.000000            61  0.032787
Business & Finance         2      0.700072  3.000000            68  0.029412
weather                    1      0.650478  3.000000            52  0.019231
Communication              1      0.700090  3.000000            67  0.014925

In [20]:
fn_rate = fn_by_category.join(category_sizes)
fn_rate["fn_rate"] = fn_rate["fn_count"] / fn_rate["total_skills"]
fn_rate.sort_values("fn_rate", ascending=False)

,fn_count,avg_baseline,avg_llm,total_skills,fn_rate
Category,,,,,
Social,8,0.209959,4.000000,50,0.160000
Food and Drink,7,0.229615,4.000000,46,0.152174
Communication,10,0.228321,4.000000,67,0.149254
Lifestyle,7,0.245035,4.142857,48,0.145833
productivity,7,0.237424,4.142857,50,0.140000
weather,7,0.246229,4.000000,52,0.134615
Game and Trivia,7,0.209786,4.142857,56,0.125000
Kids,6,0.228110,4.166667,52,0.115385
Home services,6,0.238830,4.000000,53,0.113208
Music and Audio,5,0.238848,4.000000,54,0.092593
Business & Finance,6,0.221788,4.000000,68,0.088235
Health and Fitness,5,0.229238,4.000000,61,0.081967
Shopping,5,0.226288,4.000000,63,0.079365
News,3,0.200705,4.000000,45,0.066667
Sports,3,0.233656,4.000000,46,0.065217
Smart Home,4,0.234645,4.000000,65,0.061538
Travel and Transportation,3,0.263899,4.000000,50,0.060000
Local,3,0.251194,4.000000,52,0.057692
Education & Reference,3,0.232887,4.000000,56,0.053571
Novelty and Humor,3,0.246496,4.000000,56,0.053571
Movie and TV,2,0.204130,4.000000,46,0.043478
Connected_car,2,0.256534,4.000000,49,0.040816
Utilities,1,0.207183,4.000000,59,0.016949

## 8. Category Summary

In [17]:
summary = (

    new_data.groupby("Category").agg(
        skill_count = ("Skill Name","count"),
        mean_baseline = ("baseline_risk_score","mean"),
        mean_llm_genericity_risk = ("llm_genericity_risk","mean"),
        mean_llm_ambiguity_risk = ("llm_ambiguity_risk","mean"),
        mean_llm_semantic_confusion = ("llm_semantic_confusion_risk","mean"),
        mean_llm_squatting_risk = ("llm_squatting_risk","mean"),
        mean_llm_overall_risk = ("llm_overall_risk","mean"),
        mean_llm_composite = ("llm_composite","mean"),
    ).sort_values("mean_llm_overall_risk", ascending=False).reset_index()
)
summary.to_csv("llm_category_summary.csv", index=False)
summary.round(2)

,Category,skill_count,mean_baseline,mean_llm_genericity_risk,mean_llm_ambiguity_risk,mean_llm_semantic_confusion,mean_llm_squatting_risk,mean_llm_overall_risk,mean_llm_composite
0,productivity,50,0.51,3.96,2.28,3.04,3.62,3.74,3.74
1,Social,50,0.49,3.88,2.26,2.94,3.64,3.74,3.74
2,Education & Reference,56,0.57,3.93,2.09,2.95,3.68,3.70,3.70
3,Kids,52,0.57,3.81,2.06,2.94,3.67,3.65,3.65
4,Game and Trivia,56,0.56,3.70,1.98,2.82,3.64,3.62,3.62
5,Communication,67,0.41,3.81,2.18,2.94,3.54,3.57,3.57
6,Home services,53,0.41,3.62,2.26,2.91,3.49,3.55,3.55
7,Lifestyle,48,0.50,3.81,1.88,2.83,3.56,3.54,3.54
8,Business & Finance,68,0.42,3.46,2.09,2.81,3.44,3.40,3.40
9,Travel and Transportation,50,0.42,3.58,2.06,2.78,3.44,3.38,3.38
10,Novelty and Humor,56,0.56,3.62,1.89,2.71,3.52,3.38,3.38
11,Food and Drink,46,0.49,3.61,2.04,2.76,3.39,3.37,3.37
12,Health and Fitness,61,0.44,3.62,1.87,2.70,3.38,3.33,3.33
13,Movie and TV,46,0.52,3.50,1.87,2.72,3.30,3.33,3.33
14,Local,52,0.43,3.48,2.04,2.63,3.31,3.31,3.31
15,Music and Audio,54,0.46,3.30,1.91,2.74,3.44,3.30,3.30
16,Utilities,59,0.40,3.66,1.83,2.78,3.31,3.27,3.27
17,News,45,0.47,3.47,1.93,2.80,3.47,3.27,3.27
18,Sports,46,0.52,3.48,1.78,2.70,3.43,3.26,3.26
19,Smart Home,65,0.39,3.25,2.02,2.75,3.26,3.20,3.20
20,Shopping,63,0.34,3.21,1.92,2.65,3.37,3.14,3.14
21,weather,52,0.42,3.27,1.88,2.54,3.31,3.12,3.12
22,Connected_car,49,0.39,2.90,1.82,2.55,3.06,2.94,2.94